### PR TITLE
Makes `makeIndent` publicly accessible

### PR DESCRIPTION
**Pull request by rjlohan**
Makes the `makeIndent()` function publicly accessible for consumers to capture current indenting and apply.

### CODE REVIEW

**Comment by eladb** [comment]
Can you explain why users would want to use `makeIndent` directly and via the `openBlock` method?

**Comment by rjlohan** [comment]
I've consumed this method in C# codegen, where the openBlockFormatter assumes I want `{` on the same line. So, I override with;

```
// C# standard is to put opening braces on newlines with same level of indenting
this.code.openBlockFormatter = (s?: string) => s + '\n' + this.code.makeIndent() + '{';
```

That makes sure that the opening brace is on a newline (as is the defacto standard in C#), and that it's indented correctly.

**Comment by eladb** [comment]
How about passing the indent string as a second parameter to the `openBlockFormatter`?

**Comment by rjlohan** [comment]
The indent string is a dynamic value (indent level changes throughout the code generation process), so it has to be computed when used. This is the only function marked `private` in this type currently, I think it's easier to just allow it to be consumed if required rather than complicate the rest of the interface to hide this one method.

**Pull request closed without merging**
